### ISSUE TITLE
Bullshit, I'm Chinese too

### ISSUE THREAD

**Issue by zj299792458** [ithinco/i-am-chinese-the-dragonfly-must-go-on#4]
我也是中国人，坚决反对dragonfly
不用百度你还可以用必应，用搜狗，为什么你要用谷歌？谷歌接受审查和必应搜狗360有什么区别？
你自己不愿意选择必应和搜狗，为什么要人家选择DuckDuckGo？
这是何等自私的心态？
就算谷歌真的进入中国，那551,615,600个人可能还会用百度
他们不用谷歌，正因为他们不用bing或者搜狗一样
不会有任何改变
而真正在国内使用Google的人
还需要想尽办法绕过这个限制
反而增加了门槛
估计这个issue还要被关闭
因为阻止不同意见传播已经成为了中国文化的一部分
这正是我使用Google的原因
也是我反对dragonfly的原因

Leave google along!!!!
There are many alternatives in China, such as Bing and SoGou.
Why are you so obsessed with Baidu when you claimed you're suffering?
The majority will continue with Baidu when Google comes with censorship.
Because there is no difference between google and others by that time.
The only reason I think that google doing Dragonfly is: making money from Chinese.
If that so I won't say anything because Google after all is a commercial company instead of a charity.
I'll respect this decision.
But don't claim this as a noble cause because it makes me sick.
I'm a loyal user of Google and I live in mainland China.
It's not that hard to use Google 
This issue may be closed because it contains opposite idea 
Chinese culture is always allergic to different ideas
That's the reason that I need original google

**Comment by zj299792458** [comment]
如果谷歌真的如此重要，你们应该请求zf把Google放进来，而不是请求Google自我阉割，这些事情的责任根本就不是Google，Google也没有任何义务采取行动，如果连真正有义务有能力的机构都无动于衷，寄希望于谷歌也未免太可悲了。

**Comment by darrenliuwei** [comment]
十分赞同！赞成你的意见！讲的非常好非常对！支持你！

**Comment by HaoyeTang** [comment]
中国政府当年选择支持百度就是个错误 现在我也不期望已经忘记谷歌存在的用户再回去用谷歌 但至少记得谷歌的用户可以继续用谷歌

**Comment by darrenliuwei** [comment]
> 中国政府当年选择支持百度就是个错误 现在我也不期望已经忘记谷歌存在的用户再回去用谷歌 但至少记得谷歌的用户可以继续用谷歌

现在Google公司并没有破产，想用Google的人依然可以继续使用Google。

**Comment by HaoyeTang** [comment]
> > 中国政府当年选择支持百度就是个错误 现在我也不期望已经忘记谷歌存在的用户再回去用谷歌 但至少记得谷歌的用户可以继续用谷歌
> 
> 现在Google公司并没有破产，想用Google的人依然可以继续使用Google。

并不能无障碍使用

**Comment by darrenliuwei** [comment]
> > > 中国政府当年选择支持百度就是个错误 现在我也不期望已经忘记谷歌存在的用户再回去用谷歌 但至少记得谷歌的用户可以继续用谷歌
> > 
> > 
> > 现在Google公司并没有破产，想用Google的人依然可以继续使用Google。
> 
> 并不能无障碍使用

可以随意使用

**Comment by HaoyeTang** [comment]
> > > > 中国政府当年选择支持百度就是个错误 现在我也不期望已经忘记谷歌存在的用户再回去用谷歌 但至少记得谷歌的用户可以继续用谷歌
> > > 
> > > 
> > > 现在Google公司并没有破产，想用Google的人依然可以继续使用Google。
> > 
> > 
> > 并不能无障碍使用
> 
> 可以随意使用

还是那句话，只不过是有了绕过障碍的方法 而障碍本质上没有被移除

**Comment by darrenliuwei** [comment]
> > > > > 中国政府当年选择支持百度就是个错误 现在我也不期望已经忘记谷歌存在的用户再回去用谷歌 但至少记得谷歌的用户可以继续用谷歌
> > > > 
> > > > 
> > > > 现在Google公司并没有破产，想用Google的人依然可以继续使用Google。
> > > 
> > > 
> > > 并不能无障碍使用
> > 
> > 
> > 可以随意使用
> 
> 还是那句话，只不过是有了绕过障碍的方法 而障碍本质上没有被移除

中国人花了那么多血汗钱就是为了建立这个障碍，这个障碍与Google无关，这个障碍是政府的事

**Comment by HaoyeTang** [comment]
> > > > > > 中国政府当年选择支持百度就是个错误 现在我也不期望已经忘记谷歌存在的用户再回去用谷歌 但至少记得谷歌的用户可以继续用谷歌
> > > > > 
> > > > > 
> > > > > 现在Google公司并没有破产，想用Google的人依然可以继续使用Google。
> > > > 
> > > > 
> > > > 并不能无障碍使用
> > > 
> > > 
> > > 可以随意使用
> > 
> > 
> > 还是那句话，只不过是有了绕过障碍的方法 而障碍本质上没有被移除
> 
> 中国人花了那么多血汗钱就是为了建立这个障碍，这个障碍与Google无关，这个障碍是政府的事

“If you don't like something, change it. If you can't change it, change your attitude.”

**Comment by SCLeoX** [comment]
> > > > > > > 中国政府当年选择支持百度就是个错误 现在我也不期望已经忘记谷歌存在的用户再回去用谷歌 但至少记得谷歌的用户可以继续用谷歌
> > > > > > 
> > > > > > 
> > > > > > 现在Google公司并没有破产，想用Google的人依然可以继续使用Google。
> > > > > 
> > > > > 
> > > > > 并不能无障碍使用
> > > > 
> > > > 
> > > > 可以随意使用
> > > 
> > > 
> > > 还是那句话，只不过是有了绕过障碍的方法 而障碍本质上没有被移除
> > 
> > 
> > 中国人花了那么多血汗钱就是为了建立这个障碍，这个障碍与Google无关，这个障碍是政府的事
> 
> “If you don't like something, change it. If you can't change it, change your attitude.”

首先，你完全没有理解 @darrenliuwei 的意思就在瞎反驳。中国并不会因为谷歌的引入变得开放。相反，审查后谷歌将会变成另一个百度，一个技术更好，更可以作恶的百度。

其次，你引用的这个句子有本质上就有逻辑问题。提出批评的人没有提出修改意见的义务和责任，更何况仅仅是“不喜欢”。

**Comment by HoweverL** [comment]
不是谷歌不愿服务中国人

**Comment by darrenliuwei** [comment]
呵呵，全都被关闭了，@ithinco 你没资格使用Google，你没资格讨论言论自由，鄙视你
