### ISSUE TITLE
如果Google没有退出中国，魏则西还是会毫不犹豫的选择百度搜索

### ISSUE THREAD

**Issue by darrenliuwei** [ithinco/i-am-chinese-the-dragonfly-must-go-on#5]
任何人做任何事情都无法改变想要使用百度的人去使用百度！！！
Google进入中国，百度的用户也一定还是百度的用户！

**Comment by XuJ0e** [comment]
我同意，即使现在能用上Google服务的人还是能用上，不需要阉割版的Google！

**Comment by darrenliuwei** [comment]
> 增加更多的选择 即使是阉割了也比百度好 在墙内还没观察到什么学术性网站被墙的（个人需求的）

阉割了就能让使用百度的人使用Google？？
难道百度的用户是傻子？阉割了就能吸引到他们？？
他们爱用百度，不管你Google有没有阉割，他们依然会拒绝使用Google！！！
不管如何，他们爱用百度，他们会毫不犹豫的选择百度，拒绝使用Google！

**Comment by hepin1989** [comment]
Can't you guys just use English?

**Comment by HaoyeTang** [comment]
> > 增加更多的选择 即使是阉割了也比百度好 在墙内还没观察到什么学术性网站被墙的（个人需求的）
> 
> 阉割了就能让使用百度的人使用Google？？
> 难道百度的用户是傻子？阉割了就能吸引到他们？？
> 他们爱用百度，不管你Google有没有阉割，他们依然会拒绝使用Google！！！
> 不管如何，他们爱用百度，他们会毫不犹豫的选择百度，拒绝使用Google！

那就跟我无关了 只不过是让选择用谷歌的人能用谷歌

**Comment by HaoyeTang** [comment]
> Can't you guys just use English?

English is not a necessity. We choose to use Chinese

**Comment by darrenliuwei** [comment]
> > > 增加更多的选择 即使是阉割了也比百度好 在墙内还没观察到什么学术性网站被墙的（个人需求的）
> > 
> > 
> > 阉割了就能让使用百度的人使用Google？？
> > 难道百度的用户是傻子？阉割了就能吸引到他们？？
> > 他们爱用百度，不管你Google有没有阉割，他们依然会拒绝使用Google！！！
> > 不管如何，他们爱用百度，他们会毫不犹豫的选择百度，拒绝使用Google！
> 
> 那就跟我无关了 只不过是让选择用谷歌的人能用谷歌

现在想用Google的人正在用Google呀！
不想用Google的人，拒绝用Google的人，现在也没用Google呀！

**Comment by HaoyeTang** [comment]
> > > > 增加更多的选择 即使是阉割了也比百度好 在墙内还没观察到什么学术性网站被墙的（个人需求的）
> > > 
> > > 
> > > 阉割了就能让使用百度的人使用Google？？
> > > 难道百度的用户是傻子？阉割了就能吸引到他们？？
> > > 他们爱用百度，不管你Google有没有阉割，他们依然会拒绝使用Google！！！
> > > 不管如何，他们爱用百度，他们会毫不犹豫的选择百度，拒绝使用Google！
> > 
> > 
> > 那就跟我无关了 只不过是让选择用谷歌的人能用谷歌
> 
> 现在想用Google的人正在用Google呀！
> 不想用Google的人，拒绝用Google的人，现在也没用Google呀！

无障碍使用，

**Comment by darrenliuwei** [comment]
> > > > > 增加更多的选择 即使是阉割了也比百度好 在墙内还没观察到什么学术性网站被墙的（个人需求的）
> > > > 
> > > > 
> > > > 阉割了就能让使用百度的人使用Google？？
> > > > 难道百度的用户是傻子？阉割了就能吸引到他们？？
> > > > 他们爱用百度，不管你Google有没有阉割，他们依然会拒绝使用Google！！！
> > > > 不管如何，他们爱用百度，他们会毫不犹豫的选择百度，拒绝使用Google！
> > > 
> > > 
> > > 那就跟我无关了 只不过是让选择用谷歌的人能用谷歌
> > 
> > 
> > 现在想用Google的人正在用Google呀！
> > 不想用Google的人，拒绝用Google的人，现在也没用Google呀！
> 
> 无障碍使用，

现在使用Google有障碍么？？收费的免费的网上到处都是资源，漫天飞舞。

**Comment by HaoyeTang** [comment]
> > > > > > 增加更多的选择 即使是阉割了也比百度好 在墙内还没观察到什么学术性网站被墙的（个人需求的）
> > > > > 
> > > > > 
> > > > > 阉割了就能让使用百度的人使用Google？？
> > > > > 难道百度的用户是傻子？阉割了就能吸引到他们？？
> > > > > 他们爱用百度，不管你Google有没有阉割，他们依然会拒绝使用Google！！！
> > > > > 不管如何，他们爱用百度，他们会毫不犹豫的选择百度，拒绝使用Google！
> > > > 
> > > > 
> > > > 那就跟我无关了 只不过是让选择用谷歌的人能用谷歌
> > > 
> > > 
> > > 现在想用Google的人正在用Google呀！
> > > 不想用Google的人，拒绝用Google的人，现在也没用Google呀！
> > 
> > 
> > 无障碍使用，
> 
> 现在使用Google有障碍么？？收费的免费的网上到处都是资源，漫天飞舞。

有，那些只不过是绕过障碍的方法罢了，只想从根本上移除障碍

**Comment by darrenliuwei** [comment]
> > > > > > > 增加更多的选择 即使是阉割了也比百度好 在墙内还没观察到什么学术性网站被墙的（个人需求的）
> > > > > > 
> > > > > > 
> > > > > > 阉割了就能让使用百度的人使用Google？？
> > > > > > 难道百度的用户是傻子？阉割了就能吸引到他们？？
> > > > > > 他们爱用百度，不管你Google有没有阉割，他们依然会拒绝使用Google！！！
> > > > > > 不管如何，他们爱用百度，他们会毫不犹豫的选择百度，拒绝使用Google！
> > > > > 
> > > > > 
> > > > > 那就跟我无关了 只不过是让选择用谷歌的人能用谷歌
> > > > 
> > > > 
> > > > 现在想用Google的人正在用Google呀！
> > > > 不想用Google的人，拒绝用Google的人，现在也没用Google呀！
> > > 
> > > 
> > > 无障碍使用，
> > 
> > 
> > 现在使用Google有障碍么？？收费的免费的网上到处都是资源，漫天飞舞。
> 
> 有，那些只不过是绕过障碍的方法罢了，只想从根本上移除障碍

从根本上移除，那不是Google的事，那是政府决定的！中国人花了那么多钱建立防火墙，那不是墙，那是中国人的血汗钱

**Comment by HaoyeTang** [comment]
> > > > > > > > 增加更多的选择 即使是阉割了也比百度好 在墙内还没观察到什么学术性网站被墙的（个人需求的）
> > > > > > > 
> > > > > > > 
> > > > > > > 阉割了就能让使用百度的人使用Google？？
> > > > > > > 难道百度的用户是傻子？阉割了就能吸引到他们？？
> > > > > > > 他们爱用百度，不管你Google有没有阉割，他们依然会拒绝使用Google！！！
> > > > > > > 不管如何，他们爱用百度，他们会毫不犹豫的选择百度，拒绝使用Google！
> > > > > > 
> > > > > > 
> > > > > > 那就跟我无关了 只不过是让选择用谷歌的人能用谷歌
> > > > > 
> > > > > 
> > > > > 现在想用Google的人正在用Google呀！
> > > > > 不想用Google的人，拒绝用Google的人，现在也没用Google呀！
> > > > 
> > > > 
> > > > 无障碍使用，
> > > 
> > > 
> > > 现在使用Google有障碍么？？收费的免费的网上到处都是资源，漫天飞舞。
> > 
> > 
> > 有，那些只不过是绕过障碍的方法罢了，只想从根本上移除障碍
> 
> 从根本上移除，那不是Google的事，那是政府决定的！中国人花了那么多钱建立防火墙，那不是墙，那是中国人的血汗钱

“If you don't like something, change it. If you can't change it, change your attitude.”

**Comment by lancelot1025** [comment]
墙的是什么？国内新闻说国外快完了，墙外新闻说国内快完了。我们为什么没有主观去获取这些东西的权利。墙能墙掉所有，墙也能虑掉未成年人，虑掉成年人干什么，成年人未必需要这种引导，对国民自信太差？

**Comment by tonystarksupergood** [comment]
极不支持现阶段以阉割的姿态回来 真不用说那些没有用的 什么墙阻断了自由这那的 说这些有什么用 政府的意图是要培养自己的互联网行业 九年以前谷歌facebook都不走 阿里腾讯能成长到今天？第二个原因 你能驾驭你自己 你能辨别真假对错 中国十四亿人 平均受教育水平啥样？ 个个都能确保多元文化的冲击？GFW起码在现阶段利大于弊 再说谷歌回不回来的事 回来肯定要受监管 也就是阉割 不都吵吵互联网精神互联网精神吗 这最有损互联网精神的事情 怎么就又支持了呢？再说说魏则西 这种事发生了 很悲惨 我也恨百度 但是凭什么就绑架人家谷歌呢？这repo的主人拿两张visualization 摆出一副好像我们就等Google来救了的姿态 我就想问问你 你凭啥绑架人家 这个时代 没人跟钱过不去 你环境好了 自然回来 你看看中国互联网自己的环境 除了阿里 还有几家在全力以赴 踏踏实实做硬核的东西 为了捞钱都不顾一切 就这环境你好意思吵吵让人回来？

环境不好了 我们改变环境
出了问题 先想如何自救

**Comment by HaoyeTang** [comment]
> 极不支持现阶段以阉割的姿态回来 真不用说那些没有用的 什么墙阻断了自由这那的 说这些有什么用 政府的意图是要培养自己的互联网行业 九年以前谷歌facebook都不走 阿里腾讯能成长到今天？第二个原因 你能驾驭你自己 你能辨别真假对错 中国十四亿人 平均受教育水平啥样？ 个个都能确保多元文化的冲击？GFW起码在现阶段利大于弊 再说谷歌回不回来的事 回来肯定要受监管 也就是阉割 不都吵吵互联网精神互联网精神吗 这最有损互联网精神的事情 怎么就又支持了呢？再说说魏则西 这种事发生了 很悲惨 我也恨百度 但是凭什么就绑架人家谷歌呢？这repo的主人拿两张visualization 摆出一副好像我们就等Google来救了的姿态 我就想问问你 你凭啥绑架人家 这个时代 没人跟钱过不去 你环境好了 自然回来 你看看中国互联网自己的环境 除了阿里 还有几家在全力以赴 踏踏实实做硬核的东西 为了捞钱都不顾一切 就这环境你好意思吵吵让人回来？
> 
> 环境不好了 我们改变环境
> 出了问题 先想如何自救

这种事情还是看主观意见了 其实现在就是不想看到不了解中国的谷歌员工干涉这件事 有谷歌回来肯定是个好事 当时把谷歌逼出去还不是为了培养百度 现在大家都得到充分的成长了也是时候让他回来了 反正都没几个人记得了

**Comment by tonystarksupergood** [comment]
> > 极不支持现阶段以阉割的姿态回来 真不用说那些没有用的 什么墙阻断了自由这那的 说这些有什么用 政府的意图是要培养自己的互联网行业 九年以前谷歌facebook都不走 阿里腾讯能成长到今天？第二个原因 你能驾驭你自己 你能辨别真假对错 中国十四亿人 平均受教育水平啥样？ 个个都能确保多元文化的冲击？GFW起码在现阶段利大于弊 再说谷歌回不回来的事 回来肯定要受监管 也就是阉割 不都吵吵互联网精神互联网精神吗 这最有损互联网精神的事情 怎么就又支持了呢？再说说魏则西 这种事发生了 很悲惨 我也恨百度 但是凭什么就绑架人家谷歌呢？这repo的主人拿两张visualization 摆出一副好像我们就等Google来救了的姿态 我就想问问你 你凭啥绑架人家 这个时代 没人跟钱过不去 你环境好了 自然回来 你看看中国互联网自己的环境 除了阿里 还有几家在全力以赴 踏踏实实做硬核的东西 为了捞钱都不顾一切 就这环境你好意思吵吵让人回来？
> > 环境不好了 我们改变环境
> > 出了问题 先想如何自救
> 
> 这种事情还是看主观意见了 其实现在就是不想看到不了解中国的谷歌员工干涉这件事 有谷歌回来肯定是个好事 当时把谷歌逼出去还不是为了培养百度 现在大家都得到充分的成长了也是时候让他回来了 反正都没几个人记得了

关键现在咱们还没有自己能拿出手的搜索 这时候回来 首先是阉割 其次咱们自己的搜索就很难做起来了 百度肯定是要废 就是让别人废还不如自己内部出来另一家给他废了

**Comment by Ynge** [comment]
阉割版的谷歌既违背谷歌自己的核心价值，于己有害；即便做成，无非是另一个百度，或许是功能上碾压百度，本质并无区别，因为它的核心价值观已经阉割掉了，所以于人也无太大意义。http://m.mnw.cn/news/digi/2090977.html

**Comment by darrenliuwei** [comment]
呵呵，全都被关闭了，@ithinco 你没资格使用Google，你没资格讨论言论自由，鄙视你
